CREATE TYPE service_status AS ENUM ('wait', 'success', 'denied');
create table Person
(
    id            int generated by default as identity primary key,
    login         varchar,
    name          varchar(10) not null,
    surname       varchar(30) not null,
    date_of_birth date        not null,
    password      varchar     not null,
    user_role     varchar(10),
    salary        int
);
create table Types_of_rooms
(
    type_id      int generated by default as identity primary key,
    room_type    varchar(10),
    one_day_cost int
);
create table Rooms
(
    room_id      int generated by default as identity primary key,
    room_number  int,
    room_type_id int not null references Types_of_rooms (type_id)
);

create table Booking
(
    booking_id     int generated by default as identity primary key,
    user_id        int  not null references Person (id),
    room_id        int  not null references Rooms (room_id),
    check_in_date  date not null,
    check_out_date date not null,
    status         boolean
);
create table Additional_services
(
    service_id          int generated by default as identity primary key,
    user_id             int not null references Person (id),
    service_description varchar(200),
    status              service_status,
    response_messages   varchar(200)
);
create table FeedBack
(
    feedback_id int generated by default as identity primary key,
    mark        int,
    user_id     int not null references Person (id),
    message     varchar(200)
);
