create table Person
(
    id            int generated by default as identity primary key,
    login         varchar(30),
    name          varchar(30),
    surname       varchar(30),
    date_of_birth date,
    password      varchar(30),
    user_role     varchar(10),
    salary        decimal

);
create table Article
(
    article_id int generated by default as identity primary key,
    title      varchar(50),
    stuff_id   int references Person (id),
    article    varchar
);
create table Feedback
(
    feedback_id int generated by default as identity primary key,
    mark        integer,
    user_id     int references Person (id),
    message     varchar(300)

);
create table Types_of_rooms
(
    type_id      int generated by default as identity primary key,
    room_type    varchar(10),
    one_day_cost decimal
);
create table Rooms
(
    room_id      int generated by default as identity primary key,
    room_type_id int references Types_of_rooms (type_id)

);
create table Booking
(
    booking_id     int generated by default as identity primary key,
    user_id        int references Person (id),
    room_id        int references Rooms (room_id),
    check_in_date  DATE,
    check_out_date DATE,
    summary_cost   decimal

);

create table Services
(
    service_id          int generated by default as identity primary key,
    service_name        varchar(40),
    service_description varchar(200),
    cost                decimal

);

create table Additional_services (
    add_service_id int generated by default as identity ,
    booking_id int references Booking(booking_id),
    service_id int references Services(service_id),
    comment VARCHAR(100),
    status boolean

)
