create table person
(
    id            integer generated by default as identity
        primary key,
    login         varchar(300),
    name          varchar(30),
    surname       varchar(30),
    date_of_birth date,
    password      varchar(300),
    user_role     varchar(30),
    salary        numeric
);



create table article
(
    article_id integer generated by default as identity
        primary key,
    title      varchar(50),
    stuff_id   integer
        references person,
    article    varchar
);


create table feedback
(
    feedback_id integer generated by default as identity
        primary key,
    mark        integer,
    user_id     integer
        references person,
    message     varchar(300)
);



create table types_of_rooms
(
    type_id      integer generated by default as identity
        primary key,
    room_type    varchar(10),
    one_day_cost numeric
);



create table rooms
(
    room_id      integer generated by default as identity
        primary key,
    room_type_id integer
        references types_of_rooms
);



create table booking
(
    booking_id     integer generated by default as identity
        primary key,
    user_id        integer
        references person,
    room_id        integer
        references rooms,
    check_in_date  date,
    check_out_date date,
    summary_cost   numeric
);

create table services
(
    service_id          integer generated by default as identity
        primary key,
    service_name        varchar(40),
    service_description varchar(200),
    cost                numeric
);



create table additional_services
(
    add_service_id integer generated by default as identity,
    booking_id     integer
        references booking,
    service_id     integer
        references services,
    comment        varchar(100),
    status         boolean
);
